language: ruby
rvm:
  - 2.2.3
  - 2.3.0

sudo: false
cache: bundler
before_script:
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake test_app
script:
  - export DISPLAY=:99.0
  - bundle exec rspec spec

